version: '3'
services:
  prefect-server:
    image: ghcr.io/olegpodlipalin/server_image:latest
    container_name: prefect-server
    ports:
      - "80:4200"
    volumes:
      - prefect:/root/.prefect
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PREFECT_UI_URL=http://prefect-server:4200/api
      - PREFECT_API_URL=http://prefect-server:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_KEY=${PREFECT_API_KEY}
      - PREFECT_DOCKER_WORKPOOL=${PREFECT_DOCKER_WORKPOOL}
    networks:
      - worker-pool
    healthcheck:
      test: prefect --version || exit 1
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 10s
  
  prefect-deploy-flows:
    image: ghcr.io/olegpodlipalin/prefect_flows:latest
    command: ["prefect", "deploy", "--prefect-file", "prefect.yml", "--all"]
    volumes:
      - prefect:/root/.prefect
    environment:
      - PARENT_DIR_PATH=${PARENT_DIR_PATH}
      - HOST_DIR_PATH=${HOST_DIR_PATH}
      - WORKPOOL_NAME=${PREFECT_DOCKER_WORKPOOL}
    networks:
      - worker-pool
    depends_on:
      prefect-server:
        condition: service_healthy

volumes:
  prefect:
networks:
  worker-pool: